# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 17:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, default=200, editable=False, max_digits=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='payments.Account', verbose_name='To')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='payments.Account', verbose_name='From')),
            ],
            options={
                'ordering': ('-sent_at',),
            },
        ),
    ]
